my_chassisnode: #底盘节点
  ros__parameters: 
    feedback_hz: 100.0 #底盘反馈实际速度的频率，其实尚不清楚底盘反馈的最佳频率，所以参数化后期方便调整
    max_speed : 2.0 #物理层面上的最大速度，由底盘决定


my_maincontrolnode: #主控制节点
  ros__parameters: 
    control_hz: 20.0 #主控发布速度指令的频率
    mode: patrol #切换机器人模式->对应任务一patrol，任务二point_to_point
    start_point: 2 #初始位置编号
    goal_point: 4 #目标/最终位置编号
    arrival_tolerance: 0.05 #到达目标点的容忍距离
    cruise_speed: 2.5 #巡航速度，由x,y两个方向速度取模合成，该速度至少要大于2.0才能体现底盘的作用
    brake_dist: 3.0 #拐点减速半径 

